# Generated by Django 3.1.3 on 2020-12-06 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='lineitem_points_earned',
            field=models.IntegerField(default=0),
        ),
    ]
