# Generated by Django 3.1.3 on 2020-12-08 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_orderlineitem_lineitem_points_earned'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_country',
            field=models.CharField(default='new addition', max_length=40),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_county_or_state',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_full_name',
            field=models.CharField(default='new addition', max_length=60),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_street_address1',
            field=models.CharField(default='new addition', max_length=80),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_street_address2',
            field=models.CharField(default='new addition', max_length=80),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_town_or_city',
            field=models.CharField(default='new addition', max_length=40),
        ),
    ]
