# Generated by Django 3.1.3 on 2020-12-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20201208_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='billing_country',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_full_name',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_street_address1',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_street_address2',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_town_or_city',
            field=models.CharField(default='', max_length=40),
        ),
    ]
