# Generated by Django 3.1.3 on 2020-12-09 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_auto_20201208_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='gift_purchase',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
