# Generated by Django 3.1.3 on 2020-12-09 20:15

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_order_gift_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='billing_country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='gift_purchase',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
