# Generated by Django 3.1.3 on 2020-11-28 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='CategoryToProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='Mechanic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MechanicOfProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mechanic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.mechanic')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=254, null=True)),
                ('name', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('min_players', models.IntegerField()),
                ('max_players', models.IntegerField()),
                ('min_age', models.IntegerField()),
                ('playing_time', models.IntegerField()),
                ('year_published', models.IntegerField()),
                ('designer', models.CharField(max_length=254)),
                ('publisher', models.CharField(max_length=254)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('inventory', models.IntegerField()),
                ('on_sale', models.BooleanField(blank=True, default=False, null=True)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('game_of_the_month', models.BooleanField(blank=True, default=False, null=True)),
                ('number_reviews', models.IntegerField()),
                ('rating', models.DecimalField(decimal_places=2, max_digits=6)),
                ('boxart_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('youtube_video_1', models.URLField(blank=True, max_length=1024, null=True)),
                ('youtube_video_2', models.URLField(blank=True, max_length=1024, null=True)),
                ('categories', models.ManyToManyField(blank=True, through='products.CategoryToProduct', to='products.Category')),
                ('mechanic', models.ManyToManyField(blank=True, through='products.MechanicOfProduct', to='products.Mechanic')),
            ],
        ),
        migrations.AddField(
            model_name='mechanicofproduct',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product'),
        ),
        migrations.AddField(
            model_name='categorytoproduct',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product'),
        ),
    ]
