# Generated by Django 3.1.3 on 2020-12-20 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20201218_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='friendly_name',
            field=models.CharField(blank=True, default=models.CharField(max_length=254), max_length=254),
        ),
        migrations.AlterField(
            model_name='mechanic',
            name='friendly_name',
            field=models.CharField(blank=True, default=models.CharField(max_length=254), max_length=254),
        ),
        migrations.AlterField(
            model_name='product',
            name='inventory',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='youtube_video_1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='youtube_video_2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
