# Generated by Django 3.1.3 on 2020-12-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20201226_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='mechanic',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
